### --- USER ---
### CADASTRAR
POST http://localhost:1234/cadastros/usuario
Content-Type: application/json

{
    "firstname": "Staff",
    "lastname": "Teste",
    "document": "S1",
    "type": "Staff",
    "username": "s.s",
    "password": "ss",
    "status": "Ativo",
    "token": ""
}

### LISTAR
GET http://localhost:1234/usuario/listar 


### LISTAR POR TIPO
GET http://localhost:1234/usuario/listar/Aluno
###
GET http://localhost:1234/usuario/listar/Professor
###
GET http://localhost:1234/usuario/listar/Staff


### APAGAR
GET http://localhost:1234/cadastros/usuario/apagar/P2

//----------------------------------------------------------------------------------------------------------------
### --- TREINO ---
### CADASTRAR TREINO
POST http://localhost:1234/cadastros/treino
Content-Type: application/json

{
    "date": "2020-10-19",

    "student": "5f8c4854bf3f4b0416f5f5e0",

    "teacher": "5f8c4873bf3f4b0416f5f5e1",

    "activities": [
        {
        "name": "1AtividadeTeste",
        "description": "Descricao da atividade 1",
        "concluded": false,
        "price": 10
        },
        {
        "name": "2AtividadeTeste",
        "description": "Descricao da atividade 2",
        "concluded": false,
        "price": 20
        }
    ],

    "concluded": false
}

### LISTAR
GET http://localhost:1234/listar/treino