###
GET http://localhost:1234/

###
GET http://localhost:1234/5f6d2df17bc4e02ab0e02893

###
POST http://localhost:1234/
content-type: application/json

{
    "date": "2020-08-20",
    "credits":
    [
        {
            "name": "Salário",
            "value": 5000
        },
        {
            "name": "Investimentos",
            "value": 375
        }
    ],
    "debits":
    [
        {
            "name": "Luz",
            "value": 100,
            "status": "PAGO"
        }
    ]
}