//----------------------------------------------------------------------------------------------------------------
### --- USER ---
### CADASTRAR USER
POST http://localhost:1234/cadastro/usuario
Content-Type: application/json

{
    "firstname": "APA",
    "lastname": "APA",
    "document": "444",
    "type": "Aluno",
    "username": "apa",
    "password": "password",
    "status": "Inativo",
    "token": ""
}

### CADASTRAR VARIOS USER
POST http://localhost:1234/cadastro/usuario
Content-Type: application/json

[{
    "firstname": "Douglas",
    "lastname": "Gorges",
    "document": "16071022932",
    "type": "Aluno",
    "username": "douglas.gorges",
    "password": "password",
    "status": "Ativo",
    "token": ""
},

{
    "firstname": "Vinicius",
    "lastname": "Camargo",
    "document": "38883271050",
    "type": "Aluno",
    "username": "vinicius.camargo",
    "password": "password",
    "status": "Ativo",
    "token": ""
},

{
    "firstname": "Aline",
    "lastname": "Kmiecik",
    "document": "73994674042",
    "type": "Aluno",
    "username": "aline.kmiecik",
    "password": "password",
    "status": "Ativo",
    "token": ""
},

{
    "firstname": "Sherida",
    "lastname": "Silva",
    "document": "90162422016",
    "type": "Professor",
    "username": "sherida.silva",
    "password": "password",
    "status": "Ativo",
    "token": ""
},

{
    "firstname": "Pedro",
    "lastname": "Machado",
    "document": "27119239082",
    "type": "Professor",
    "username": "pedro.machado",
    "password": "password",
    "status": "Ativo",
    "token": ""
}]

### LISTAR USER
GET http://localhost:1234/lista/usuario


### LISTAR USER POR TIPO
GET http://localhost:1234/lista/usuario/Aluno
###
GET http://localhost:1234/lista/usuario/Professor
###
GET http://localhost:1234/lista/usuario/Staff

### BUSCAR USER POR Documento
GET http://localhost:1234/lista/usuario///16071022932

### BUSCAR USER POR ID
GET http://localhost:1234/lista/usuario//5f95ccfbfd82d14bc491ba48

### UPDATE USER
POST http://localhost:1234/cadastro/usuario/update/5f95b5c1116f2b128c7abc98
Content-Type: application/json

{
    "firstname": "Douglas",
    "lastname": "Gorges Updated",
    "document": "16071022932",
    "type": "Aluno",
    "username": "douglas.gorges",
    "password": "password",
    "status": "Ativo",
    "token": ""
}

### APAGAR USER by document
GET http://localhost:1234/cadastro/usuario/apagar/333

### APAGAR USER by id
DELETE http://localhost:1234/cadastro/usuario/apagar//5f95ccfbfd82d14bc491ba48


//----------------------------------------------------------------------------------------------------------------
### --- TREINO ---
### CADASTRAR TREINO
POST http://localhost:1234/cadastro/treino
Content-Type: application/json

{
    "date": "2021-10-19",
    "student": "5f95b5c1116f2b128c7abc98",
    "teacher": "5f95b5c1116f2b128c7abc9b",
    "activities": [
        {
        "name": "3AtividadeTeste",
        "description": "Descricao da atividade 1",
        "concluded": false,
        "price": 30
        },
        {
        "name": "4AtividadeTeste",
        "description": "Descricao da atividade 2",
        "concluded": false,
        "price": 40
        }
    ],

    "concluded": false
}

### LISTAR TREINO
GET http://localhost:1234/lista/treino

### BUSCAR TREINO POR ID
GET http://localhost:1234/lista/treino/5f94a268fedd482c85a2dc9f

### BUSCAR PRECO DO TREINO POR ID
GET http://localhost:1234/lista/treino/price/5f95b657116f2b128c7abca0

### UPDATE TREINO
POST http://localhost:1234/cadastro/treino/update/5f94a40f585d242e4fadf49a
Content-Type: application/json

{
    "date": "2020-10-24",
    "student": "5f8c4854bf3f4b0416f5f5e0",
    "teacher": "5f8c4873bf3f4b0416f5f5e1",
    "activities": [
        {
        "name": "3AtividadeTeste",
        "description": "Descricao da atividade 3",
        "concluded": false,
        "price": 30
        },
        {
        "name": "4AtividadeTeste",
        "description": "Descricao da atividade 4",
        "concluded": false,
        "price": 40
        }
    ],

    "concluded": false
}


### APAGAR TREINO
DELETE http://localhost:1234/cadastro/treino/apagar/5f94a268fedd482c85a2dc9f



//----------------------------------------------------------------------------------------------------------------
### --- MENSALIDADE ---
### CADASTRAR MENSALIDADE
POST http://localhost:1234/cadastro/mensalidade
Content-Type: application/json

{
    "date": "2020-10-19",
    "student": "5f8c4854bf3f4b0416f5f5e0",
    "price": 5,
    "payed": false
}

### LISTAR MENSALIDADE
GET http://localhost:1234/lista/mensalidade

### BUSCAR MENSALIDADE POR ID
GET http://localhost:1234/lista/mensalidade/5f8cb63f9e4e41062826a61f

### UPDATE MENSALIDADE
POST http://localhost:1234/cadastro/mensalidade/update/5f8cb63f9e4e41062826a61f
Content-Type: application/json

{
    "date": "2021-10-19",
    "student": "5f8c4854bf3f4b0416f5f5e0",
    "price": 5,
    "payed": false
}

### APAGAR MENSALIDADE
DELETE http://localhost:1234/cadastro/mensalidade/apagar/5f8cb63f9e4e41062826a61f


//----------------------------------------------------------------------------------------------------------------